package view;


import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Prescription;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author namv2
 */
public class PanelPrescription extends javax.swing.JPanel {
private Main parentFrame;
    private List<Prescription> listPrescriptions;

    public PanelPrescription() {
        initComponents();
        BTNEvent();
    }

    // Phương thức setParentFrame để nhận JFrame cha
    public void setParentFrame(Main parentFrame) {
        this.parentFrame = parentFrame;
    }

    private void BTNEvent() {
        btnTaoDonThuoc.addActionListener(e -> {
            FrameCreatePrescription frame = new FrameCreatePrescription();
            frame.SetParentFrame(parentFrame);
            frame.setVisible(true);
            parentFrame.dispose();
        });
    }

    // Phương thức SetPrescriptionList để nhận danh sách Prescription và cập nhật bảng
    public void SetPrescriptionList(List<Prescription> listPrescriptions) {
        this.listPrescriptions = listPrescriptions;
        updateTable();  // Cập nhật bảng sau khi set danh sách
    }

    // Phương thức để cập nhật dữ liệu trong bảng
    private void updateTable() {
        // Đặt dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tbPrescription.getModel();
        model.setRowCount(0);  // Xóa tất cả các hàng hiện tại trong bảng
        
        // Lặp qua danh sách đơn thuốc và thêm chúng vào bảng
        for (Prescription prescription : listPrescriptions) {
            Object[] row = new Object[] {
                prescription.getId(),
                prescription.getCreatedDate(), 
                prescription.getStatus(),
                prescription.getCustomerId(),
                prescription.getPromotionId(),
                prescription.getTotalPrice(),
                prescription.getDiscountAmount(),
                prescription.getFinalPrice(),
                prescription.getNote()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTaoDonThuoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPrescription = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnTaoDonThuoc.setText("Tạo đơn thuốc");

        tbPrescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ngày tạo", "Trạng thái", "Khách hàng", "Khuyến mãi", "Tổng đơn", "Lượng giảm giá", "Tiền trả", "note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPrescription);
        if (tbPrescription.getColumnModel().getColumnCount() > 0) {
            tbPrescription.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbPrescription.getColumnModel().getColumn(8).setPreferredWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh sách các đơn thuốc đã được tạo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTaoDonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoDonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoDonThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPrescription;
    // End of variables declaration//GEN-END:variables
}
